### ISSUE TITLE
The CPU usage is very high

### ISSUE THREAD

**Issue by piqihaha** [Trangoul1988/docker-grass-desktop#4]
hello brother
In grass 4.29, the CPU usage is very low
But after upgrading to 4.30
The CPU usage is very high, is this the case for you too?

**Comment by piqihaha** [comment]
![image](https://github.com/user-attachments/assets/d92aefbb-183c-44c9-85f2-701f08e9fb2f)

**Comment by Trangoul1988** [comment]
> ![image](https://private-user-images.githubusercontent.com/25221169/395794514-d92aefbb-183c-44c9-85f2-701f08e9fb2f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQyOTE4NDgsIm5iZiI6MTczNDI5MTU0OCwicGF0aCI6Ii8yNTIyMTE2OS8zOTU3OTQ1MTQtZDkyYWVmYmItMTgzYy00NGM5LTg1ZjItNzAxZjA4ZTlmYjJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE1VDE5MzkwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlOWZhMGQ5Njc5NTA2NmI0MzQ5ZjA1MGY3YTY1MjhjNDk0NmQ0NzI2ZGIzNWRmMDBkNDQ5MGIwNjg3NjUwNzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Gchs0l5_j5bqPgfJZP1Aqpd0jyz6F4T-YPL2DAGYUxM)

There is no reason to run the docker multiple times if they are on the same network. Or are thoose different public IP-s?

**Comment by Trangoul1988** [comment]
@piqihaha just restart your containers now, it should be okay now, just need a reconnecting.
